### ISSUE TITLE
Reporte

### ISSUE THREAD

**Issue by uzias10** [SistemasTecTlaxiaco/diseno-de-control-para-cajas-de-texto-uzias10#2]
[Reporte TextBox.pdf](https://github.com/SistemasTecTlaxiaco/diseno-de-control-para-cajas-de-texto-uzias10/files/6333598/Reporte.TextBox.pdf)

**Comment by Anthony4523** [comment]
Calificación: 20

Calificó: Antonio González

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
